[profile.default]
src = 'src'
out = 'out'
libs = ['dependencies']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
optimizer = true
optimizer_runs = 1000000

# Try to make sure the optimizer doesn't touch the output in a way that can break
# source maps for debugging.
# via_ir = false
# optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0

bytecode_hash = "none"
cbor_metadata = false
remappings = [
    "forge-std/=dependencies/forge-std-1.16.1/src/",
    "rain.factory/=dependencies/rain-factory-0.1.1/",
    "rain.interpreter.interface/=dependencies/rain-interpreter-interface-0.1.0/src/",
    "rain.solmem/=dependencies/rain-solmem-0.1.3/src/",
    "openzeppelin-contracts-upgradeable/contracts/=dependencies/@openzeppelin-contracts-upgradeable-5.6.1/",
    "openzeppelin-contracts/contracts/=dependencies/@openzeppelin-contracts-5.6.1/",
    "openzeppelin/=dependencies/@openzeppelin-contracts-upgradeable-5.6.1/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.6.1/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.6.1/",
]

[fuzz]
runs = 2048
seed = "0xdeadbeef"

[dependencies]
forge-std = "1.16.1"
"@openzeppelin-contracts" = "5.6.1"
"@openzeppelin-contracts-upgradeable" = "5.6.1"
rain-factory = "0.1.1"
rain-interpreter-interface = "0.1.0"
rain-math-fixedpoint = "0.2.0"
rain-solmem = "0.1.3"
rain-lib-hash = "0.1.0"
rain-math-float = "0.1.1"
rain-metadata = "0.1.0"
rain-lib-typecast = "0.1.0"

[soldeer]
recursive_deps = false
